### ISSUE TITLE
Signals not rendered correctly

### ISSUE THREAD

**Issue by gabrielrad** [wavedrom/wavedrom#260] opened 2019-10-01 08:27 UTC
Inside **_test-reg.html_** file from the **_test_** folder, swap the first _**signal**_ with the **_reg_** below, and you will observe when this happens the signal is not normally rendered anymore. For some reason when the first script is a reg it changes the way signals are drawn.
![Selection_008](https://user-images.githubusercontent.com/54810282/65946195-451acb80-e43e-11e9-84c0-aa7f5f313935.png)

After the change:
![Selection_009](https://user-images.githubusercontent.com/54810282/65946238-67144e00-e43e-11e9-82a7-c1c604cb35f5.png)

**Comment by drom** [comment] 2019-10-01 18:37
duplicate of #258

**Closed by drom** 2019-10-01 18:37 UTC
